samueltl21/restaurantreview

app/templates/base.html
app/templates/home.html

linking the login & register button in home.html #22 and also linking login (navbar)

linking the button in home

---

app/templates/restaurants.html

Added "FlavorTown" as a dummy restaurant

Created Restaurants page with only one restaurant

---

app/routes.py

adding route for restaurants.html

modiify routes to link the restaurants page

---

app/__init__.py
app/models.py
app/routes.py
app/static/script.js
app/templates/base.html
app/templates/home.html
app/templates/login.html
app/templates/sign_up.html

create user database #19 
update __init__.py
create models.py
update routes.py
adding secret key in init (temporary)
add flashed message
add hashed-password

19 create user database

---

app/templates/base.html

move flashed message location from above footer to under navbar #35

move flashed message to below navbar

---

app/routes.py
app/static/script.js
app/templates/base.html
app/templates/home.html
app/templates/login.html

make session for user
after login:
hello greeting in navbar
user able to see link to profile, restaurant, and logout.
the login link & button and sign up button at home disappear
if it's non user:
they only can see link to login and restaurant
the login link & button and sign up button appear to non user

31 make session for user

---

app/__init__.py
app/config.py

move some content from init to config.py
modify init
create .env

38 move secretkey from init to env

---

app/config.py

in config.py:
include basedir and default location, following the guide in from lab (database part)

include basedir and default location in config.py

---

app/config.py

update default_database_location for databse_uri

update default_database_location for databse_uri

---

app/__init__.py
app/models.py
app/routes.py
config.py

apply flask migrate following the database lab

47 applying flask migrate

---

app/static/styles.css
app/templates/restaurants.html

Sync restaurant page

---

app/templates/restaurants.html
app/templates/upload_reviews.html

separate css-js-on restaurants page, delete upload_review page

separate css-js-on restaurants page, delete upload_review page

---

app/routes.py
app/static/styles.css
app/templates/base.html
app/templates/restaurants.html

Set restaurant page as home, adjust login and sign up button

Set restaurant page as home

---

app/config.py

remove config from app folder

---

app/routes.py
app/templates/base.html
app/templates/upload_reviews.html

Csv features

---

app/forms.py
app/routes.py
app/templates/login.html
app/templates/sign_up.html
application-env/bin/email_validator
init_db.py
requirements.txt

create forms.py
modifying sign_up.html and login.html
modifying routes.py
add email_validator to requirements.txt

74 applying wtf forms

---

app/__init__.py
app/models.py
app/routes.py
app/templates/base.html

implementing login manager (edit __init__.py, models.py, routes.py)
edit base.html from session to user.is_authenticated

76 implementing flask login

---

app/static/styles.css
app/templates/base.html

fixing flashed message
(edit base.html and styles.css)

fixing flashed message

---

app/templates/profile.html

navigation button on profile page

comment out for page navigation on profile page

---

app/forms.py
app/routes.py
app/templates/upload_reviews.html

update upload_review.html
routes.py
forms.py

implement wtform for restaurant review

---

app/routes.py
app/static/script.js
app/templates/restaurant_detail.html
app/templates/restaurants.html

create restaurant detail page
add js for showupload form for restaurant
add restaurant detail page and upload image in routes

Restaurant detail feature

---

app/routes.py
app/static/script.js
app/templates/profile.html
app/templates/shared_reviews.html

This pull request introduces a new feature that allows users to select specific reviews from their profile and generate a tokenized shareable link. The functionality was implemented by adding a backend route to create secure tokens and a new page to display the shared reviews. On the frontend, users can now select reviews using checkboxes and click a button to generate and copy the link directly to their clipboard, making it easy to share their reviews with others.

Feature: Added share selected reviews functionality with tokenized link

---

app/templates/restaurants.html

fixing the login and signup button. it should be disappear when user is login

fixing login and signup button with is_authenticated

---

app/routes.py

accidentally delete login route from previous update.
put it back

put back login route

---

app/routes.py

avoid duplicate in sharing page

avoid duplicate in sharing page

---

app/templates/profile.html
app/templates/restaurants.html

fixing restaurant layout and link resturant in profile page

fixing restaurant layout and link resturant in profile page

---

app/static/styles.css

fixing spacing in css file

---

app/templates/profile.html

Fixed the chart alignment issue on the profile page. Now both graphs stay centered properly even on mobile or narrow screens by adding Bootstrap flex utilities inside the card body. Tested on different screen sizes to ensure it looks clean and consistent.

fix-graph-center-issue112

---

app/routes.py
app/templates/edit_review.html

This PR adds the edit review functionality, allowing users to modify their previously submitted reviews. It includes a new route, form handling, and a dedicated template. Users can now edit the rating, date, spending and restaurant details with proper validation and feedback. This enhancement improves user experience and closes #91.

Feature: Added edit review functionality

---

app/routes.py
app/static/script.js
app/templates/profile.html
app/templates/restaurant_detail.html
app/templates/shared_conversation.html
app/templates/shared_reviews.html

make the image appear on the review
fixing sharing feature

Fixing upload image review & fixing sharing feature

---

app/controllers.py
app/routes.py

separate routes.py and controllers.py

separate routes.py and controllers.py

---

app/controllers.py
app/templates/profile.html

fixing pagination and layout on profile page

fixing pagination and layout on profile page

---

app/templates/restaurants.html

change to top 3 restaurant based on review

top 3 restaurant based on review

---

app/controllers.py

fix the statistic to show all data not only on the current page

fix the statistic to show all data not only on the current page

---

app/static/styles.css
app/templates/profile.html
app/templates/shared_conversation.html
app/templates/shared_with.html
app/templates/upload_reviews.html

make the button and the page navigation on profile, upload page uniform (styling)

make styling uniform

---

app/__init__.py
app/blueprints.py
app/controllers.py
app/routes.py
app/templates/base.html
app/templates/login.html
app/templates/profile.html
app/templates/restaurant_detail.html
app/templates/restaurants.html
app/templates/shared_conversation.html
app/templates/shared_with.html
app/templates/sign_up.html
config.py
tests/test_auth.py

unit testing for authentication:
succesful login
failed login (wrong password)
sign up new user
sign up existing email (email already registered)
test logout
access profile page after logout

testing for authentication, adjust routes, adjust html page

---

application-env/bin/wsdump
seed.py
tests/test_selenium_sharing_review.py

1. create selenium test for sharing review
2. modify seed data

create selenium test and modifying seed data

---

README.md
tests/test_auth.py

edit test_auth and modify readme file

Fix test auth and add readme

---

README.md
app/controllers.py
app/forms.py
app/static/script.js
app/templates/restaurants.html
app/templates/upload_reviews.html
seed.py
tests/test_restaurant_review.py

unittest for review restaurant:
1. test review existing restaurant
2. test review new restaurant
3. test missing rating
4. test missing restaurant name
5. test all field missing
6. test negative spending amount
7. test upload valid image review
8. test upload invalid file as image

Add unit testing for review

---

app/templates/restaurant_detail.html

fixing layout for restaurant detail page

fixing layout for restaurant detail page

---

app/static/styles.css
tests/test_selenium_edit_review.py
tests/test_selenium_login.py
tests/test_selenium_navigating_after_login.py
tests/test_selenium_navigating_without_login.py

Create more selenium test
1. login
2. navigating without login
3. navigating after login
4. edit review

Create more selenium test

---

app/controllers.py
app/templates/about_us.html
app/templates/base.html
app/templates/profile.html
app/templates/restaurants.html
app/templates/upload_reviews.html
tests/test_selenium_edit_review.py
tests/test_selenium_login.py
tests/test_selenium_navigating_after_login.py
tests/test_selenium_navigating_without_login.py
tests/test_selenium_sharing_review.py

finishing touch, adjust comment and about us

finishing touch
